### PR TITLE
upgrade dependencies

### PR DESCRIPTION
**Pull request by courcelan**
upgrade axios to 1.3.6, webpack to 5.81.0

### CODE REVIEW

**Comment by ViolanteCodes** [comment]
@courcelan should we do a version bump and changelog on this?

**Comment by courcelan** [comment]
Yes that’s correct.

Cobey Potter | Wellfire Interactive
***@***.***
434.989.4862

**Comment by ViolanteCodes** [comment]
@courcelan i had to rebase due to conflicts with the previous merged PR - I think this okay (installs good, tests are passing), but can you take another look just to make sure?

**Comment by ViolanteCodes** [comment]
[Review Jest Testing PR for Buttercms-js](https://trello.com/c/fU5B1Nb7/2050-review-jest-testing-pr-for-buttercms-js)

**Comment by courcelan** [comment]
Hi @ViolanteCodes, just re-ran yarn to get the right lockfile into place, but all looks good from here. Thanks

**Review by ViolanteCodes — APPROVED** [review]
LGTM

**Pull request merged**
