### PR TITLE
update response structure to echo schema expected from TS defs and v1

### PR DESCRIPTION
**Pull request by courcelan**
This updates the response structure to echo schema expected from TypeScript definitions and the same data schema/structure as return in buttercms-js version 1.

The response no longer returns the `xsrfCookieName`, `xsrfHeaderName`, and `maxContentLength` in `response.config` as they are not in use by native fetch. Additionally, `response.config` returns  only the fully formed `url` (`response.config.url`) rather than breaking it down in discrete parts. If needed, please use the native `URL` API in your code to get similar datapoints.

This PR fixes the issues raised in https://github.com/ButterCMS/buttercms-js/issues/89.

bump package version to 2.1.0

### CODE REVIEW

**Comment by ViolanteCodes** [comment]
@courcelan I'm wondering if maybe it would be good to get @zanderle as a second reviewer on this one (since Orly is out?) I'm not the best person to review SDK changes and this SDK is pretty important. 

However, I know that in order to get the autoversionining and CI/CD to deploy, the commit message has to start with `fix:` or `feat:` - https://github.com/ButterCMS/buttercms-js/blob/master/CONTRIBUTING.md - can you squash these and change the commit message? That should also fix the failing tests on the first commit since the unit-test fix will be in the same commit as the commit that causes the failure - WDYT?

**Comment by courcelan** [comment]
squashed with the feat prefix and added @zanderle to review.

**Review by marcinpece-apptension — APPROVED** [review]
https://share.zight.com/Bluv9g24
https://share.zight.com/8LuN84AJ
https://share.zight.com/Wnu8O4Ge
LGTM 🎉

**Review by zanderle — APPROVED** [review]
LGTM 👍

**Pull request merged**
