### PR TITLE
Improve typescript support

### PR DESCRIPTION
**Pull request by WanFoxOne**
- Add namespace
- Add declaration exportation

### CODE REVIEW

**Comment by jakelumetta** [comment]
@jkelin do these changes look ok to you?

**Comment by jkelin** [comment]
I really am no typescript expert, so I think it would be best if @WanFoxOne could explain their rationale for these changes?

**Comment by WanFoxOne** [comment]
Sure. 

The problem with the current declaration file is that the interfaces cannot be imported.

For example, in vuejs, it is necessary to augment the module like this :

```ts
import { ButterStatic } from "buttercms";

declare module "vue/types/vue" {
  interface Vue {
    $buttercms: ButterStatic;
  }
}
```

I have also placed all the statements in a namespace for better organization.

**Comment by jakelumetta** [comment]
Sounds good. Thanks for the patch!

**Comment by jakelumetta** [comment]
@WanFoxOne 1.2.2 deployed

**Pull request merged**
