### PR TITLE
chore(deps): Update dependencies

### PR DESCRIPTION
**Pull request by martinalbert**
This PR merges unresolved PRs from dependabot (#37, #38, #41, #44, #45, #46), updates `axios` and `uglify-js` to new versions and adds `webpack-cli` because running webpack v4 or later from CLI requires also package `webpack-cli` (According to [webpack docs](https://webpack.js.org/guides/installation/)).

`npm-check-updates` output:
```
 axios      ~0.21.1  →   ~1.2.5
 uglify-js  ^2.8.22  →  ^3.17.4
```

### Major changes
- `axios`
  - [v1 changes](https://github.com/axios/axios/blob/v1.x/CHANGELOG.md#100---2022-10-04)
  - minor versions from `0.21` to `0.27` also contain [breaking changes](https://github.com/axios/axios/blob/main/CHANGELOG.md)
- `uglify-js` does not have major changes noted, but should fix ReDoS (more info [here](https://security.snyk.io/package/npm/uglify-js))

### `npm audit`
- on `master` branch found 27 vulnerabilities (4 low, 6 moderate, 12 high, 5 critical)
- after `npm audit fix` found 6 vulnerabilities (2 moderate, 3 high, 1 critical)
- after update of dependencies found 0 vulnerabilities

### CODE REVIEW

**Comment by ViolanteCodes** [comment]
@courcelan let me know what you think on this one?

**Review by courcelan — APPROVED** [review]
LGTM

**Review by ViolanteCodes — APPROVED** [review]
LGTM

**Comment by MrLoh** [comment]
Could you please release a new version with these changes, since it fixes security vulnerabilities.

**Pull request merged**
