### PR TITLE
upgrade to Node v20

### PR DESCRIPTION
**Pull request by courcelan**
Node v20 has moved into LTS and we are matching our library to their LTS.

Please check that it operates for you.

@violanteCodes - we'll need a refresher on how to move this to version 3.0.0 (its currently at 2.3.1) and we'll need to tag the current master for NPM use I think

### CODE REVIEW

**Comment by courcelan** [comment]
[Upgrade ButterCMS JS SDK to run on Node 20](https://trello.com/c/Qwbn3xDB/2918-upgrade-buttercms-js-sdk-to-run-on-node-20)

**Comment by ViolanteCodes** [comment]
@courcelan 

I believe we just need to add `!` to commit message:

https://github.com/google-github-actions/release-please-action#how-should-i-write-my-commits

so I think it would be `feat!: upgrade to node 20`

**Review by marcinpece-apptension — APPROVED** [review]
on wrong node version https://share.zight.com/P8uKlWKn ✅ 
on correct node version https://share.zight.com/GGub0L9L ✅ 
tests passed https://share.zight.com/8LuWZdKk ✅ 

LGTM 🎉

**Comment by ViolanteCodes** [comment]
> I believe we just need to add `!` to commit message:
> 
> https://github.com/google-github-actions/release-please-action#how-should-i-write-my-commits
> 
> so I think it would be `feat!: upgrade to node 20`

@courcelan if you fix commit message, I can re-check and merge

**Comment by courcelan** [comment]
@ViolanteCodes good for your review / release

**Review by ViolanteCodes — APPROVED** [review]
LGTM

**Pull request merged**
