### PR TITLE
Implement unit-tests with jest

### PR DESCRIPTION
**Pull request by mahdikhashan**
I'm trying to implement some tests to improve the code quality of the CMS I use and like.

### CODE REVIEW

**Review by courcelan — APPROVED** [review]
LGTM

**Comment by ViolanteCodes** [comment]
[Review Jest Testing PR for Buttercms-js](https://trello.com/c/fU5B1Nb7/2050-review-jest-testing-pr-for-buttercms-js)

**Review by courcelan — APPROVED** [review]
LGTM

**Comment by mahdikhashan** [comment]
Just to let you know that this PR is not completely done by me so merge it on your will.

**Pull request merged**
