### PR TITLE
fix: issue calling axios.create undefined

### PR DESCRIPTION
**Pull request by prokopsimek**
The problem is with v1 and in combination with commonjs module such as this SDK.

https://github.com/axios/axios/issues/5011

### CODE REVIEW

**Comment by ViolanteCodes** [comment]
@courcelan do you think you could take a look at this PR?

**Review by courcelan — APPROVED** [review]
Able to successfully connect to the Butter API

**Comment by courcelan** [comment]
@ViolanteCodes ran this on the customer's sample repo and was able to successfully connect to Butter. LGTM

**Comment by ViolanteCodes** [comment]
[User receives type error when attempting to access data through API (buttercms-js)](https://trello.com/c/jDnu7lob/2231-user-receives-type-error-when-attempting-to-access-data-through-api-buttercms-js)

**Pull request merged**
