### PR TITLE
Add missing locale param to Content and Page types

### PR DESCRIPTION
**Pull request by soniaklimas**
Added the missing `locale` parameter in butter.d.ts to support localized content retrieval.

This change ensures we can pass `locale` directly when retrieving pages and content, maintaining type safety and avoiding workarounds in code.

### CODE REVIEW

**Comment by courcelan** [comment]
hi @soniaklimas thanks for this PR! We do have a recently accepted one that seems to cover this issue, but we will keep your PR open and take another look once those other open PRs are merged into master.

We appreciate your help!

**Review by courcelan — COMMENTED** [review]
holding for re-review after merging in #108

**Comment by ViolanteCodes** [comment]
@soniaklimas are you able to resolve the merge conflict and prefix your commit message with `fix`? If not, let us know and we will handle, thank you!

**Comment by soniaklimas** [comment]
> @soniaklimas are you able to resolve the merge conflict and prefix your commit message with `fix`? If not, let us know and we will handle, thank you!

I’d appreciate it if you could handle prefixing my commit. Please let me know if there’s anything else you need from my end.

**Comment by ViolanteCodes** [comment]
@soniaklimas On review, it looks like these changes were already added with the last change to master - @courcelan can you confirm? If so, I will close this PR

**Comment by courcelan** [comment]
@ViolanteCodes correct, these were already added in the last change to master.

**Pull request closed without merging**
